name: book_list_riverpod_sample_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.17
  flutter_riverpod: ^1.0.4
  flutter_slidable: ^1.3.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
